#arsoft_articulo_homepage:
#    path: /hello/{name}
#    defaults: { _controller: ARSOFTArticuloBundle:Default:index }

#arsoft_articulos_index:
#    path: /listado
#    defaults: { _controller: ARSOFTArticuloBundle:Default:listar_articulos }

#mostrar_articulo:
#    path: /articulos/{id}
#    defaults: { _controller: ARSOFTArticuloBundle:Default:mostrar_articulo, id: 2 }



listar_articulos:
    path: /articulo/listar
    defaults: { _controller: 'ARSOFTArticuloBundle:Articulo:listarArticulos' }

crear_articulo:
    path: /articulo/crear
    defaults: { _controller: 'ARSOFTArticuloBundle:Articulo:crearArticulo' }

modificar_articulo:
    path: /articulo/modificar/{id}/{titulo_nuevo}
    defaults: { _controller: 'ARSOFTArticuloBundle:Articulo:modificarTitulo' }
    requirements:
        id: \d+

eliminar_articulo:
    path: /articulo/eliminar/{id}
    defaults: { _controller: 'ARSOFTArticuloBundle:Articulo:eliminarArticulo' }
    requirements:
        id: \d+

mostrar_articulo:
    path: /articulo/mostrar/{id}
    defaults: { _controller: ARSOFTArticuloBundle:Articulo:visualizarArticulo }
    requirements:
        id: \d+
