arsoft_articulo_homepage:
    path: /hello/{name}
    defaults: { _controller: ARSOFTArticuloBundle:Default:index }

arsoft_articulos_index:
    path: /listado
    defaults: { _controller: ARSOFTArticuloBundle:Default:listar_articulos }

mostrar_articulo:
    path: /articulos/{id}
    defaults: { _controller: ARSOFTArticuloBundle:Default:mostrar_articulo, id: 2 }
