arsoft_articulo_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ARSOFTArticuloBundle:Default:index }

arsoft_articulos_index:
    pattern: /listado
    defaults: { _controller: ARSOFTArticuloBundle:Default:listar }

arsoft_articulos_show:
    pattern: /articulos/{id}
    defaults: { _controller: ARSOFTArticuloBundle:Default:show, id: 2 }



