listar_articulos:
    path: /articulos
    defaults: { _controller: 'ARSOFTArticuloBundle:Articulo:listarArticulos' }

crear_articulo_sin_type:
    path: /articulos/crear
    defaults: { _controller: 'ARSOFTArticuloBundle:Articulo:crearArticuloSinType' }

crear_articulo_con_type:
    path: /articulos/crearType
    defaults: { _controller: 'ARSOFTArticuloBundle:Articulo:crearArticuloConType' }

modificar_articulo:
    path: /articulos/modificar/{id}/{titulo_nuevo}
    defaults: { _controller: 'ARSOFTArticuloBundle:Articulo:modificarTitulo' }
    requirements:
        id: \d+

eliminar_articulo:
    path: /articulos/eliminar/{id}
    defaults: { _controller: 'ARSOFTArticuloBundle:Articulo:eliminarArticulo' }
    requirements:
        id: \d+

mostrar_articulo:
    path: /articulos/{id}
    defaults: { _controller: ARSOFTArticuloBundle:Articulo:visualizarArticulo }
    requirements:
        id: \d+

comentario_crear_sin_type:
    path: /articulos/{articuloId}/comentario/crear
    defaults: { _controller: ARSOFTArticuloBundle:Comentario:crearComentarioSinType }

comentario_crear_con_type:
    path: /articulos/{articuloId}/comentario/crearType
    defaults: { _controller: ARSOFTArticuloBundle:Comentario:crearComentarioConType }



